# Generated by Django 5.0.1 on 2024-01-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='etd',
            field=models.CharField(default='5 Days', max_length=100),
        ),
    ]
