# Generated by Django 5.0.1 on 2024-01-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_etd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='etd',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
