# Generated by Django 5.0.1 on 2024-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata',
            name='follow_update',
            field=models.DateField(blank=True, default=None),
        ),
    ]
